//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductRecoAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRecommender
    {
        public int Id { get; set; }
        public string ProductCategory { get; set; }
        public string SubCategory { get; set; }
        public string Manufacturer { get; set; }
        public string RecommendedResult { get; set; }
    }
}
